services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: elasticsearch
    volumes:
    - esdata:/usr/share/elasticsearch/data
    environment:
    - node.name=elasticsearch
    - discovery.type=single-node
    - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    - xpack.security.enabled=true
    - xpack.security.http.ssl.enabled=false
    - xpack.security.transport.ssl.enabled=false
    - ES_JAVA_OPTS=-Xms512m -Xmx512m
    healthcheck:
      test: ["CMD-SHELL", "curl -sf -u elastic:${ELASTIC_PASSWORD} http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=1s || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 30s
    ports:
      - "9200:9200"
    networks:
     - otel-net
     
  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.0
    container_name: kibana
    environment:
    - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    - ELASTICSEARCH_SERVICEACCOUNTTOKEN=${TOKEN_ES}
    - XPACK_SECURITY_ENCRYPTIONKEY=${XPACK_SECURITY_ENCRYPTIONKEY}
    - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=${XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY}
    - XPACK_REPORTING_ENCRYPTIONKEY=${XPACK_REPORTING_ENCRYPTIONKEY}
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy  
    networks:
      - otel-net 
  apm-server:
    image: docker.elastic.co/apm/apm-server:8.14.0
    container_name: apm-server
    command: >
        apm-server -e
          -E output.elasticsearch.hosts=["http://elasticsearch:9200"]
          -E output.elasticsearch.username=elastic
          -E output.elasticsearch.password=${ELASTIC_PASSWORD}
          -E apm-server.host="0.0.0.0:8200"
          -E apm-server.data_streams.wait_for_integration=false
          -E apm-server.auth.secret_token=${SECRET_TOKEN_APM_SERVER}
    ports:
      - "8200:8200"
    depends_on:
      elasticsearch:
        condition: service_healthy  
    networks:
      - otel-net

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.154.0
    container_name: otel-collector
    volumes:
      - ./collector/otel-collector.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
    depends_on:
      - apm-server
    networks:
      - otel-net
    
  app:
    build: ./app
    container_name: app
    environment:
      OTEL_SERVICE_NAME: fastapi-demo
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
    ports:
      - 8080:8080
    depends_on:
      - otel-collector
    networks:
      - otel-net

networks:
  otel-net:
    driver: bridge
volumes:
  esdata:
    driver: local